Simplifying setup.sh
zokradonh/kopano-docker pull request #43
Opened 2018-12-02 11:53 UTC by nupplaphil

FQDN is now used to create default base DN and default domain for postmaster.

Part of #42

2018-12-02 12:26 UTC, nupplaphil commented
- The guessed base DN is now based on the FQDN
- The timezone is guessed based on the local system
- If the default LDAP (= bundled) server is used, the PW is now random
- If the default DB (= bundeld) is used, the PW is now random

2018-12-02 21:24 UTC, fbartels commented
Thanks for your pr. I will need a bit of time to go through the changes, since I am on holiday until Saturday and do not have a full system to play with it. Will check back next weekend.

2018-12-09 21:16 UTC, fbartels commented on setup.sh
> +		LDAP_SEARCH_BASE="$LDAP_BIND_DN"
when just entering the setup, the ldap_search_base is empty for me.

2018-12-09 21:16 UTC, fbartels commented on setup.sh
> +	LDAP_BASE_DN=$(fqdn_to_dn $FQDN)
move this down just above line 41?

2018-12-09 21:16 UTC, fbartels commented on setup.sh
> +		LDAP_SEARCH_BASE="$LDAP_BIND_DN"
it should be LDAP_BASE_DN instead of LDAP_BIND_DN

2018-12-09 21:16 UTC, fbartels commented on setup.sh
> +		read -p "Password of the admin user [$value_default]: " new_value
When not using the bundled ldap then we do not have to differentiate between  admin/read-only user. remove the ldap_admin_password option.

2018-12-09 21:16 UTC, fbartels commented on setup.sh
> +		read -p "Password for the MySQL root user [$value_default]: " new_value
here its the same as with the ldap image. root user not needed, we just need a user to query the database (and potentially create tables)

2018-12-09 21:39 UTC, fbartels commented
Maybe at the end of setup.sh print something like "hey, you specified a different ldap/db than what is bundled with compose. Remember to remove these from the compose file"

2018-12-10 06:51 UTC, fbartels requested changes
obligatory comment to mark this pr as "request changes"

2018-12-10 19:30 UTC, nupplaphil commented
I had to rebase because of missing changes in the setup

2018-12-11 06:54 UTC, fbartels approved these changes

2018-12-11 06:54 UTC, merged

2018-12-11 06:55 UTC, fbartels commented
Thanks looks good now. I saw a smaller thing in the casing of the ldap dns, will fix that after merge myself.